[2016-12-19 19:49:39.315] [ERROR] cache-error - { Error: connect ETIMEDOUT 120.25.116.90:80
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  cause: 
   { Error: connect ETIMEDOUT 120.25.116.90:80
       at Object.exports._errnoException (util.js:1012:11)
       at exports._exceptionWithHostPort (util.js:1035:20)
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
     message: 'connect ETIMEDOUT 120.25.116.90:80',
     code: 'NetworkingError',
     errno: 'ETIMEDOUT',
     syscall: 'connect',
     address: '120.25.116.90',
     port: 80,
     region: null,
     hostname: 'cachetest.cn-hangzhou.ots.aliyuncs.com',
     retryable: true,
     time: 2016-12-19T11:49:39.263Z },
  isOperational: true,
  code: 'NetworkingError',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '120.25.116.90',
  port: 80,
  region: null,
  hostname: 'cachetest.cn-hangzhou.ots.aliyuncs.com',
  retryable: true,
  time: 2016-12-19T11:49:39.263Z }
[2016-12-19 19:49:39.344] [ERROR] cache-error - { Error: connect ETIMEDOUT 120.25.116.90:80
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  cause: 
   { Error: connect ETIMEDOUT 120.25.116.90:80
       at Object.exports._errnoException (util.js:1012:11)
       at exports._exceptionWithHostPort (util.js:1035:20)
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
     message: 'connect ETIMEDOUT 120.25.116.90:80',
     code: 'NetworkingError',
     errno: 'ETIMEDOUT',
     syscall: 'connect',
     address: '120.25.116.90',
     port: 80,
     region: null,
     hostname: 'cachetest.cn-hangzhou.ots.aliyuncs.com',
     retryable: true,
     time: 2016-12-19T11:49:39.334Z },
  isOperational: true,
  code: 'NetworkingError',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '120.25.116.90',
  port: 80,
  region: null,
  hostname: 'cachetest.cn-hangzhou.ots.aliyuncs.com',
  retryable: true,
  time: 2016-12-19T11:49:39.334Z }
[2016-12-19 19:49:39.541] [ERROR] cache-error - { Error: connect ETIMEDOUT 120.25.116.90:80
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  cause: 
   { Error: connect ETIMEDOUT 120.25.116.90:80
       at Object.exports._errnoException (util.js:1012:11)
       at exports._exceptionWithHostPort (util.js:1035:20)
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
     message: 'connect ETIMEDOUT 120.25.116.90:80',
     code: 'NetworkingError',
     errno: 'ETIMEDOUT',
     syscall: 'connect',
     address: '120.25.116.90',
     port: 80,
     region: null,
     hostname: 'cachetest.cn-hangzhou.ots.aliyuncs.com',
     retryable: true,
     time: 2016-12-19T11:49:39.532Z },
  isOperational: true,
  code: 'NetworkingError',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '120.25.116.90',
  port: 80,
  region: null,
  hostname: 'cachetest.cn-hangzhou.ots.aliyuncs.com',
  retryable: true,
  time: 2016-12-19T11:49:39.532Z }
[2016-12-19 19:49:52.311] [ERROR] cache-error - { Error: connect ETIMEDOUT 120.25.116.90:80
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  cause: 
   { Error: connect ETIMEDOUT 120.25.116.90:80
       at Object.exports._errnoException (util.js:1012:11)
       at exports._exceptionWithHostPort (util.js:1035:20)
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
     message: 'connect ETIMEDOUT 120.25.116.90:80',
     code: 'NetworkingError',
     errno: 'ETIMEDOUT',
     syscall: 'connect',
     address: '120.25.116.90',
     port: 80,
     region: null,
     hostname: 'cachetest.cn-hangzhou.ots.aliyuncs.com',
     retryable: true,
     time: 2016-12-19T11:49:52.288Z },
  isOperational: true,
  code: 'NetworkingError',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '120.25.116.90',
  port: 80,
  region: null,
  hostname: 'cachetest.cn-hangzhou.ots.aliyuncs.com',
  retryable: true,
  time: 2016-12-19T11:49:52.288Z }
[2016-12-19 19:49:52.319] [ERROR] cache-error - { Error: connect ETIMEDOUT 120.25.116.90:80
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  cause: 
   { Error: connect ETIMEDOUT 120.25.116.90:80
       at Object.exports._errnoException (util.js:1012:11)
       at exports._exceptionWithHostPort (util.js:1035:20)
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
     message: 'connect ETIMEDOUT 120.25.116.90:80',
     code: 'NetworkingError',
     errno: 'ETIMEDOUT',
     syscall: 'connect',
     address: '120.25.116.90',
     port: 80,
     region: null,
     hostname: 'cachetest.cn-hangzhou.ots.aliyuncs.com',
     retryable: true,
     time: 2016-12-19T11:49:52.315Z },
  isOperational: true,
  code: 'NetworkingError',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '120.25.116.90',
  port: 80,
  region: null,
  hostname: 'cachetest.cn-hangzhou.ots.aliyuncs.com',
  retryable: true,
  time: 2016-12-19T11:49:52.315Z }
[2016-12-19 19:49:52.324] [ERROR] cache-error - { Error: connect ETIMEDOUT 120.25.116.90:80
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  cause: 
   { Error: connect ETIMEDOUT 120.25.116.90:80
       at Object.exports._errnoException (util.js:1012:11)
       at exports._exceptionWithHostPort (util.js:1035:20)
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
     message: 'connect ETIMEDOUT 120.25.116.90:80',
     code: 'NetworkingError',
     errno: 'ETIMEDOUT',
     syscall: 'connect',
     address: '120.25.116.90',
     port: 80,
     region: null,
     hostname: 'cachetest.cn-hangzhou.ots.aliyuncs.com',
     retryable: true,
     time: 2016-12-19T11:49:52.315Z },
  isOperational: true,
  code: 'NetworkingError',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '120.25.116.90',
  port: 80,
  region: null,
  hostname: 'cachetest.cn-hangzhou.ots.aliyuncs.com',
  retryable: true,
  time: 2016-12-19T11:49:52.315Z }
[2016-12-19 19:49:52.329] [ERROR] cache-error - { Error: connect ETIMEDOUT 120.25.116.90:80
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  cause: 
   { Error: connect ETIMEDOUT 120.25.116.90:80
       at Object.exports._errnoException (util.js:1012:11)
       at exports._exceptionWithHostPort (util.js:1035:20)
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
     message: 'connect ETIMEDOUT 120.25.116.90:80',
     code: 'NetworkingError',
     errno: 'ETIMEDOUT',
     syscall: 'connect',
     address: '120.25.116.90',
     port: 80,
     region: null,
     hostname: 'cachetest.cn-hangzhou.ots.aliyuncs.com',
     retryable: true,
     time: 2016-12-19T11:49:52.316Z },
  isOperational: true,
  code: 'NetworkingError',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '120.25.116.90',
  port: 80,
  region: null,
  hostname: 'cachetest.cn-hangzhou.ots.aliyuncs.com',
  retryable: true,
  time: 2016-12-19T11:49:52.316Z }
[2016-12-19 19:49:52.333] [ERROR] cache-error - { Error: connect ETIMEDOUT 120.25.116.90:80
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  cause: 
   { Error: connect ETIMEDOUT 120.25.116.90:80
       at Object.exports._errnoException (util.js:1012:11)
       at exports._exceptionWithHostPort (util.js:1035:20)
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
     message: 'connect ETIMEDOUT 120.25.116.90:80',
     code: 'NetworkingError',
     errno: 'ETIMEDOUT',
     syscall: 'connect',
     address: '120.25.116.90',
     port: 80,
     region: null,
     hostname: 'cachetest.cn-hangzhou.ots.aliyuncs.com',
     retryable: true,
     time: 2016-12-19T11:49:52.316Z },
  isOperational: true,
  code: 'NetworkingError',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '120.25.116.90',
  port: 80,
  region: null,
  hostname: 'cachetest.cn-hangzhou.ots.aliyuncs.com',
  retryable: true,
  time: 2016-12-19T11:49:52.316Z }
[2016-12-19 19:53:34.003] [ERROR] cache-error - { Error: connect ETIMEDOUT 120.25.116.90:80
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  cause: 
   { Error: connect ETIMEDOUT 120.25.116.90:80
       at Object.exports._errnoException (util.js:1012:11)
       at exports._exceptionWithHostPort (util.js:1035:20)
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
     message: 'connect ETIMEDOUT 120.25.116.90:80',
     code: 'NetworkingError',
     errno: 'ETIMEDOUT',
     syscall: 'connect',
     address: '120.25.116.90',
     port: 80,
     region: null,
     hostname: 'cachetest.cn-hangzhou.ots.aliyuncs.com',
     retryable: true,
     time: 2016-12-19T11:53:33.954Z },
  isOperational: true,
  code: 'NetworkingError',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '120.25.116.90',
  port: 80,
  region: null,
  hostname: 'cachetest.cn-hangzhou.ots.aliyuncs.com',
  retryable: true,
  time: 2016-12-19T11:53:33.954Z }
[2016-12-19 19:53:44.339] [ERROR] cache-error - { Error: connect ETIMEDOUT 120.25.116.90:80
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  cause: 
   { Error: connect ETIMEDOUT 120.25.116.90:80
       at Object.exports._errnoException (util.js:1012:11)
       at exports._exceptionWithHostPort (util.js:1035:20)
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
     message: 'connect ETIMEDOUT 120.25.116.90:80',
     code: 'NetworkingError',
     errno: 'ETIMEDOUT',
     syscall: 'connect',
     address: '120.25.116.90',
     port: 80,
     region: null,
     hostname: 'cachetest.cn-hangzhou.ots.aliyuncs.com',
     retryable: true,
     time: 2016-12-19T11:53:44.326Z },
  isOperational: true,
  code: 'NetworkingError',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '120.25.116.90',
  port: 80,
  region: null,
  hostname: 'cachetest.cn-hangzhou.ots.aliyuncs.com',
  retryable: true,
  time: 2016-12-19T11:53:44.326Z }
[2016-12-19 19:53:44.466] [ERROR] cache-error - { Error: connect ETIMEDOUT 120.25.116.90:80
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  cause: 
   { Error: connect ETIMEDOUT 120.25.116.90:80
       at Object.exports._errnoException (util.js:1012:11)
       at exports._exceptionWithHostPort (util.js:1035:20)
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
     message: 'connect ETIMEDOUT 120.25.116.90:80',
     code: 'NetworkingError',
     errno: 'ETIMEDOUT',
     syscall: 'connect',
     address: '120.25.116.90',
     port: 80,
     region: null,
     hostname: 'cachetest.cn-hangzhou.ots.aliyuncs.com',
     retryable: true,
     time: 2016-12-19T11:53:44.458Z },
  isOperational: true,
  code: 'NetworkingError',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '120.25.116.90',
  port: 80,
  region: null,
  hostname: 'cachetest.cn-hangzhou.ots.aliyuncs.com',
  retryable: true,
  time: 2016-12-19T11:53:44.458Z }
[2016-12-19 19:53:44.536] [ERROR] cache-error - { Error: connect ETIMEDOUT 120.25.116.90:80
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  cause: 
   { Error: connect ETIMEDOUT 120.25.116.90:80
       at Object.exports._errnoException (util.js:1012:11)
       at exports._exceptionWithHostPort (util.js:1035:20)
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
     message: 'connect ETIMEDOUT 120.25.116.90:80',
     code: 'NetworkingError',
     errno: 'ETIMEDOUT',
     syscall: 'connect',
     address: '120.25.116.90',
     port: 80,
     region: null,
     hostname: 'cachetest.cn-hangzhou.ots.aliyuncs.com',
     retryable: true,
     time: 2016-12-19T11:53:44.533Z },
  isOperational: true,
  code: 'NetworkingError',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '120.25.116.90',
  port: 80,
  region: null,
  hostname: 'cachetest.cn-hangzhou.ots.aliyuncs.com',
  retryable: true,
  time: 2016-12-19T11:53:44.533Z }
